/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8c049055-3505-4d33-ad63-330fcaba8369",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_NZPxe6lHm",
    "aws_user_pools_web_client_id": "44e8e7d3k0654jg5ejsllfpipc",
    "oauth": {
        "domain": "authlernae9dd11d-ae9dd11d-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://authlern.vercel.app/",
        "redirectSignOut": "https://authlern.vercel.app/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
